language: node_js
node_js:
- "12"

cache:
  yarn: true
  directories:
  - "node_modules"

script:
- yarn fix

os:
- linux

before_install:
- npm install -g yarn@^1.9.4 --cache-min 999999999

install:
- yarn
